Style coding and updates server killing process.

diff --git a/vpl-jail-system.initd b/vpl-jail-system.initd
--- a/vpl-jail-system.initd
+++ b/vpl-jail-system.initd
@@ -29,19 +29,42 @@
 #          |     |___ pts #Replicate original
 #          |     |___ shm #tmpfs
 #          |___ etc       #Replaced passwd and group
-#          |___ home      #tmfs dir to create apropiate prisoner home dir
+#          |___ home      #tmfs dir to create suitable prisoner home dir
 #          |___ proc      #Real dir by mount --bind
 #          |___ run       #tmpfs
 #          |     |___ lock #tmpfs
-# load init.d common functions
-. /lib/lsb/init-functions
 
 LOGFILE=/etc/vpl/vpl-jail-service.log
 DEAMON=/etc/vpl/vpl-jail-server
-PIDFILE=/var/run/vpl-jail-server.pid
+PIDFILE=/run/vpl-jail-server.pid
 NOMOUNT="^vpl|^init|^ldap|^udev|grub|^rc[0-6S]|^pam|^cron|^apm|^logrotate"
 NOMOUNT="$NOMOUNT|^mail|^rsyslog|^shadow|^security|^ssl|^ssh|^update"
-read_config_var(){
+
+if [ "$(command -v systemctl)" = "" ] ; then
+	# Try to use lsb init-functions
+	if [ -x  /lib/lsb/init-functions ] ; then
+		. /lib/lsb/init-functions
+	fi
+fi
+# If lsb init-functions not working define owns
+declare -f log_failure_msg &> /dev/null
+if [ "$?" == "1" ] ; then 
+	function log_failure_msg {
+		echo $1
+	}
+	function log_success_msg {
+		echo $1
+	}
+fi
+
+declare -f start_daemon &> /dev/null
+if [ "$?" == "1" ] ; then 
+	function start_daemon {
+		$1 $2 $3 &
+	}
+fi
+
+function read_config_var {
 	local FILE=$1
 	shift
 	while (( "$#" )); do
@@ -60,7 +83,7 @@ read_config_var(){
 	done
 }
 
-create_check_dir() {
+function create_check_dir {
 	if [ -d "$1" ] ; then
 		if [ "$(stat -c "%d:%i" /)" == "$(stat -c "%d:%i" $1)" ] ; then
 			log_failure_msg $"vpl-jail-system error in configuration: root directory used"
@@ -77,7 +100,8 @@ create_check_dir() {
 		exit 1
 	fi
 }
-run_root_script() {
+
+function run_root_script {
 	if [ -s "$1" ] ; then
 		if [ "$(stat -c '%u' $1)" = "0" ] ; then
 			$1
@@ -86,14 +110,15 @@ run_root_script() {
 		fi
 	fi
 }
-pre_start() {
+
+function pre_start {
 	run_root_script /etc/vpl/pre_start.sh
 }
-post_stop() {
+function post_stop {
 	run_root_script /etc/vpl/post_stop.sh
 }
 
-set_etc() {
+function set_etc {
 	#passwd file
 	local PASSWORDFILE="$JAILPATH/etc/passwd"
 	local I
@@ -114,28 +139,28 @@ set_etc() {
 	chmod 600 "$SHADOWFILE"
 }
 
-set_tmpdir() {
+function set_tmpdir {
 	if [ "$2" == "" ] ; then
-		echo "Error mounting $JAILPATH/$1 : no SIZE set"
+		echo "Error mounting $JAILPATH$1 : no SIZE set"
 	fi
 	local mask=0711
 	if [ "$3" != "" ] ; then
 		mask=$3
 	fi
 	unset_tmpdir $1
-	create_check_dir "$JAILPATH/$1" $mask
+	create_check_dir "$JAILPATH$1" $mask
 	if [ "$USETMPFS" != "false" ] ; then 
-		mount -t tmpfs -osize="$2" tmpfs "$JAILPATH/$1"
+		mount -t tmpfs -osize="$2" tmpfs "$JAILPATH$1"
 	fi
 }
 
-unset_tmpdir() {
-	if mountpoint -q "$JAILPATH/$1"; then
-		umount "$JAILPATH/$1"
+function unset_tmpdir {
+	if mountpoint -q "$JAILPATH$1"; then
+		umount "$JAILPATH$1"
 	fi
 }
 
-set_other() {
+function set_other {
 	if [ -d $1 ] ; then
 		create_check_dir "$JAILPATH$1" $(stat -c %a $1)
 		mount --bind $1 "$JAILPATH$1"
@@ -143,13 +168,13 @@ set_other() {
 	fi
 }
 
-unset_other() {
+function unset_other {
 	if [ -d $1 -a -d "$JAILPATH$1" ] ; then
 		umount -l -f "$JAILPATH$1"
 	fi
 }
 
-set_firewall() {
+function set_firewall {
 #0: No firewall
 #1: VPL service+DNS+ full internet access
 #2: VPL service+DNS+ Limit internet to port 80 and 443 (super user unlimited)
@@ -197,7 +222,7 @@ set_firewall() {
 	fi
 }
 
-unset_firewall() {
+function unset_firewall {
 	#try to remove the VPL config in any case
 	{
 		iptables -D INPUT -j VPL_IN
@@ -211,7 +236,7 @@ unset_firewall() {
 	} &> /dev/null
 }
 
-read_config() {
+function read_config {
 	local VPLJAIL_INSTALL_DIR=/etc/vpl
 	case "$1" in
   		start)
@@ -246,7 +271,7 @@ read_config() {
 	fi
 }
 
-start_vpl() {
+function start_vpl {
 	if [ -f $PIDFILE ] ; then
 		stop_vpl
 	fi
@@ -264,7 +289,7 @@ start_vpl() {
 		rm -R "$JAIL_WORK/*" &> /dev/null
 		mount -t overlay overlay -olowerdir=/,upperdir=$JAIL_LIVE,workdir=$JAIL_WORK${NOSUID} "$JAILPATH"
 		if [ "$?" != "0" ] ; then
-			log_failure_msg $"Error mountig jail dir"
+			log_failure_msg $"Error mounting jail dir"
 			exit 1
 		fi
 		set_etc
@@ -281,17 +306,21 @@ start_vpl() {
 	sleep 1
 	if [ -f $PIDFILE ] ; then
 		set_firewall $1
-		log_success_msg $"Starting vpl-jail-system service:"
 	else
 		log_failure_msg $"Daemon not started"
 	fi
 }
 
-stop_vpl() {
+function stop_vpl {
 	{
 		read_config stop
-		killproc /etc/vpl/vpl-jail-server 15
+		if [ "$(command -v killproc)" != "" ] ; then
+			killproc /etc/vpl/vpl-jail-server 15
+		fi
 		if [ -f $PIDFILE ] ; then
+			kill -15 $(cat $PIDFILE) &> /dev/null
+			sleep 1
+			kill -9 $(cat $PIDFILE) &> /dev/null
 			rm $PIDFILE
 		fi
 		if [ -d "$JAILPATH" ] ; then
@@ -314,28 +343,31 @@ stop_vpl() {
 		unset_firewall
 		post_stop
 	} 2>> $LOGFILE
-	log_success_msg $"Stopping vpl-jail-system service:"
 }
 
 echo "===== vpl-jail-system ====== $1 $2 $3" >> $LOGFILE
 date >> $LOGFILE
 case "$1" in
   start)
+		log_success_msg $"Starting vpl-jail-system service:"
         start_vpl $2 $3
         ;;
   stop)
+  		log_success_msg $"Stopping vpl-jail-system service:"
         stop_vpl
         ;;
   restart)
+  		log_success_msg $"Restarting vpl-jail-system service:"
         stop_vpl
         start_vpl
         ;;
   force-reload)
+  		log_success_msg $"Force-reload vpl-jail-system service:"
         stop_vpl
         start_vpl
         ;;
   status)
-        pidofproc /etc/vpl/vpl-jail-server
+        pidof /etc/vpl/vpl-jail-server
 	    exit $? 
         ;;
 *)
